"""
Markdown Reporter — writes the final audit_report.md from scored findings.
Each finding section includes: file, severity, description, suggestion,
complexity estimates, and CWE/OWASP references.
"""
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List

from scanners.base import Finding, Severity


_SEVERITY_EMOJI = {
    "CRITICAL": "🔴",
    "HIGH":     "🟠",
    "MEDIUM":   "🟡",
    "LOW":      "🔵",
    "INFO":     "⚪",
}

_PRIORITY_LABEL = {"P0": "Critical — Block Deploy", "P1": "High — Fix This Sprint",
                   "P2": "Medium — Fix This Quarter", "P3": "Low / Informational"}


def write_report(scored: Dict[str, Any], repo_path: str, output_path: str = "audit_report.md"):
    lines: List[str] = []
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    summary = scored["summary"]
    buckets = scored["by_priority"]

    # ── Header ────────────────────────────────────────────────────────────
    lines += [
        f"# dbt / Snowflake Security & Performance Audit Report",
        f"",
        f"**Repository:** `{repo_path}`  ",
        f"**Generated:** {now}  ",
        f"**Risk Score:** {scored['risk_score']}/100 — **{scored['risk_label']}**",
        f"",
        "---",
        "",
    ]

    # ── Executive Summary ─────────────────────────────────────────────────
    lines += [
        "## Executive Summary",
        "",
        "| Priority | Count | Severity |",
        "|----------|-------|----------|",
    ]
    for p in ["P0", "P1", "P2", "P3"]:
        count = len(buckets[p])
        label = _PRIORITY_LABEL[p]
        lines.append(f"| **{p}** | {count} | {label} |")

    lines += [
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ]
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
        emoji = _SEVERITY_EMOJI[sev]
        lines.append(f"| {emoji} {sev} | {summary.get(sev, 0)} |")

    lines += ["", "---", ""]

    # ── Findings by priority ──────────────────────────────────────────────
    for p in ["P0", "P1", "P2", "P3"]:
        group = buckets[p]
        if not group:
            continue

        lines += [
            f"## {p} — {_PRIORITY_LABEL[p]}",
            "",
        ]

        for i, f in enumerate(group, 1):
            emoji = _SEVERITY_EMOJI.get(f.severity.value, "⚪")
            lines += [
                f"### {emoji} [{f.check_id}] {f.title}",
                "",
                f"| Field | Value |",
                f"|-------|-------|",
                f"| **File** | `{f.file}` |",
                f"| **Line** | {f.line if f.line else '—'} |",
                f"| **Severity** | {f.severity.value} |",
                f"| **Category** | {f.category.value} |",
            ]
            if f.cwe:
                lines.append(f"| **CWE** | [{f.cwe}](https://cwe.mitre.org/data/definitions/{f.cwe.replace('CWE-','')}.html) |")
            if f.owasp:
                lines.append(f"| **OWASP** | {f.owasp} |")
            if f.time_complexity:
                lines.append(f"| **Time Complexity** | `{f.time_complexity}` |")
            if f.space_complexity:
                lines.append(f"| **Space Complexity** | `{f.space_complexity}` |")

            lines += [""]

            if f.description:
                lines += [
                    "**Description**",
                    "",
                    f.description,
                    "",
                ]

            if f.code_snippet:
                lines += [
                    "**Affected Code**",
                    "",
                    "```sql" if f.category.value.startswith("sql") else "```python",
                    f.code_snippet.strip(),
                    "```",
                    "",
                ]

            if f.suggestion:
                lines += [
                    "**Suggested Fix**",
                    "",
                    "```",
                    f.suggestion.strip(),
                    "```",
                    "",
                ]

            lines += ["---", ""]

    # ── Footer ────────────────────────────────────────────────────────────
    lines += [
        "## How to Re-Run",
        "",
        "```bash",
        "# Static scan only (fast, ~30 seconds)",
        "python audit_agent/main.py /path/to/repo",
        "",
        "# Full scan with AI explanation",
        "python audit_agent/main.py /path/to/repo --mode full",
        "```",
        "",
        f"*Report generated by audit_agent — {now}*",
    ]

    Path(output_path).write_text("\n".join(lines), encoding="utf-8")
    print(f"Report written to: {output_path}")
    return output_path
